### ISSUE TITLE
missing POM file in repo

### ISSUE THREAD

**Issue by maggu2810** [wborn/nrjavaserial-builder#1]
Hi @wborn,

I realized that the POM file is missing in the Maven repo.
See: https://openhab.jfrog.io/openhab/libs-release/org/openhab/nrjavaserial/3.15.0.OH2/

Can you fix that?

**Comment by wborn** [comment]
I also saw these warnings for the missing POM in Eclipse since we switched to the bnd build. The reason why it wasn't added is probably because the POM is not a build artifact since nrjavaserial is build with Gradle. We could create a POM for it and then perhaps @kaikreuzer can upload it to the OH libs-release repo?

**Comment by maggu2810** [comment]
I cannot judge "why" it is missing, but I would expect a similar one to that one: https://repo1.maven.org/maven2/com/neuronrobotics/nrjavaserial/3.15.0/nrjavaserial-3.15.0.pom
Sure some modified coordinates, but the dependencies should be equal.

**Comment by wborn** [comment]
The missing POMs have been added to the [releases](https://github.com/wborn/nrjavaserial-builder/releases/).

**Comment by wborn** [comment]
Closing this issue because the POM is now also available at:
https://openhab.jfrog.io/openhab/libs-release/org/openhab/nrjavaserial/3.15.0.OH2/nrjavaserial-3.15.0.OH2.pom
